accounts/urls.py
from unicodedata import name
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView 
from .views import SignUpView


app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/',SignUpView.as_view(), name='signup'),

]

blog/urls.py
from re import U
from unicodedata import name
from django.urls import path
from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView
    )


app_name = 'blog'
urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('post/create', BlogCreateView.as_view(), name='post_create'),
    path('post/update/<int:pk>', BlogUpdateView.as_view(), name='post_update'),
    path('post/delete/<int:pk>', BlogDeleteView.as_view(), name='post_delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('posts/', include('posts.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView


urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),

]

posts/urls.py
from unicodedata import name
from django.urls import path
from .views import HomePageView

app_name = 'posts'
urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.urls import reverse
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.pk})
    

posts/models.py
from django.db import models


class Post(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('accounts:login')

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
    )
from .models import Post


class BlogListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'


class BlogDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


class BlogCreateView(CreateView):
    model = Post
    template_name = 'blog/post_create.html'
    fields = ['title', 'author', 'body']


class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post_update.html'
    fields = ['title', 'body']


class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('blog:home')

pages/views.py
from re import template
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'pages/home.html'


class AboutPageView(TemplateView):
    template_name = 'pages/about.html'

posts/views.py
from operator import ge
from pyexpat import model
from re import I
from unittest import mock
from django.views.generic import ListView
from .models import Post

class HomePageView(ListView):
    model = Post
    template_name = 'posts/home.html'
    context_object_name = 'all_posts'

templates/blog/base.html
{% load static %}
<html>
<head>
<title>Django blog</title>
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesh\
eet">
<link href="{% static 'blog/css/base.css' %}" rel="stylesheet"s>
</head>
<body>
<div>
<header>
<div class="nav-left">
<h1><a href="{% url 'blog:home' %}">Django blog</a></h1>
</div>
<div class="nav-right">
<a href="{% url 'blog:post_create' %}">+ New Blog Post</a>
</div>
</header>

{% if user.is_authenticated %}
    <p>Hi {{ user.username }}!</p>
    <p><a href="{% url 'accounts:logout' %}">Log out</a></p>
{% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'accounts:login' %}">Log In</a>
{% endif %}


{% block content %}
{% endblock content %}
</div>
</body>
</html>

templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}

    {% for post in posts %}
        <div class="post-entry">
            <h2><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.body }}</p>
        </div>
    {% endfor %}

{% endblock content %}

templates/blog/post_create.html
{% extends 'blog/base.html' %}

{% block content %}

    <h1>New post</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock content %}

templates/blog/post_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete post</h1>

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
        <input type="submit" value="Confirm">
    </form>

{% endblock content %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="post-entry">
<h2>{{ post.title }}</h2>
<p>{{ post.body }}</p>
</div>

<a href="{% url 'blog:post_update' post.pk %}">+ Edit Blog Post</a>
<p><a href="{% url 'post_delete' post.pk %}">+ Delete Blog Post</a></p>
{% endblock content %}

templates/blog/post_update.html
{% extends 'blog/base.html' %}

{% block content %}

<h1>Edit post</h1>

    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

{% endblock content %}

templates/pages/about.html
{% extends 'pages/base.html' %}

{% block content %}
    <h1>About page</h1>
{% endblock content %}

templates/pages/base.html
<header>
    <a href="{% url 'home' %}">Home</a> |
    <a href="{% url 'about' %}">About</a>
</header>
    {% block content %}
    {% endblock content %}

templates/pages/home.html
{% extends 'pages/base.html' %}

{% block content %}
    <h1>Homepage</h1>
{% endblock content %}

templates/posts/home.html
<h1>Message board homepage</h1>
<hr>
<ul>
    {% for post in all_posts %}
        <li>{{ post.text }}</li>
    {% endfor %}
</ul>